global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: redis
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: api
    static_configs:
      - targets: ['api:8080']

  - job_name: worker
    static_configs:
      - targets: ['worker:8080']

  - job_name: vault
    metrics_path: /v1/sys/metrics
    static_configs:
      - targets: ['vault:8200']
